/**
 * D:\\Code\\Hala\\gitlab.hala\\Services\\loan-origination-system\\LoanOriginationSystem\\LoanOriginationSystem.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';

import { Observable } from 'rxjs';

import { BASE_PATH, COLLECTION_FORMATS } from './variables';
import { ChangeOfferModel } from '../../models/los/changeOfferModel';
import { LoanApplicationModel } from '../../models/los/loanApplicationModel';
import { OfferDetailsModel } from '../../models/los/offerDetailsModel';

@Injectable()
export class LoanOriginationService {
  protected basePath = 'https://localhost:59881';
  public defaultHeaders = new HttpHeaders();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
  }

  public apiV1LoanOriginationAcceptOfferByCashierPost(
    body?: ChangeOfferModel,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<OfferDetailsModel> {
    let headers = this.defaultHeaders;

    return this.httpClient.request<OfferDetailsModel>(
      'post',
      `${this.basePath}/api/v1/LoanOrigination/AcceptOfferByCashier`,
      {
        body: body,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  //   public apiV1LoanOriginationAcceptOfferByOwnerPost(
  //     body?: ChangeOfferModel,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'post',
  //       `${this.basePath}/api/v1/LoanOrigination/AcceptOfferByOwner`,
  //       {
  //         body: body,
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationCreateLoanApplicationPost(
  //     body?: LoanApplicationModel,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'post',
  //       `${this.basePath}/api/v1/LoanOrigination/CreateLoanApplication`,
  //       {
  //         body: body,
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetFinalOfferLOSIdGet(
  //     lOSId: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     if (lOSId === null || lOSId === undefined) {
  //       throw new Error(
  //         'Required parameter lOSId was null or undefined when calling apiV1LoanOriginationGetFinalOfferLOSIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetFinalOffer/${encodeURIComponent(
  //         String(lOSId)
  //       )}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetLoanApplicationLOSIdGet(
  //     lOSId: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<LoanApplicationModel> {
  //     if (lOSId === null || lOSId === undefined) {
  //       throw new Error(
  //         'Required parameter lOSId was null or undefined when calling apiV1LoanOriginationGetLoanApplicationLOSIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<LoanApplicationModel>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetLoanApplication/${encodeURIComponent(
  //         String(lOSId)
  //       )}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetLoanApplicationsByCashierCashierIdGet(
  //     cashierId: number,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<Array<LoanApplicationModel>> {
  //     if (cashierId === null || cashierId === undefined) {
  //       throw new Error(
  //         'Required parameter cashierId was null or undefined when calling apiV1LoanOriginationGetLoanApplicationsByCashierCashierIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<Array<LoanApplicationModel>>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetLoanApplicationsByCashier/${encodeURIComponent(
  //         String(cashierId)
  //       )}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetLoanApplicationsByOwnerEntityIdGet(
  //     entityId: number,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<Array<LoanApplicationModel>> {
  //     if (entityId === null || entityId === undefined) {
  //       throw new Error(
  //         'Required parameter entityId was null or undefined when calling apiV1LoanOriginationGetLoanApplicationsByOwnerEntityIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<Array<LoanApplicationModel>>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetLoanApplicationsByOwner/${encodeURIComponent(
  //         String(entityId)
  //       )}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetLoanApplicationsCRNumberGet(
  //     cRNumber: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<Array<LoanApplicationModel>> {
  //     if (cRNumber === null || cRNumber === undefined) {
  //       throw new Error(
  //         'Required parameter cRNumber was null or undefined when calling apiV1LoanOriginationGetLoanApplicationsCRNumberGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<Array<LoanApplicationModel>>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetLoanApplications/${encodeURIComponent(
  //         String(cRNumber)
  //       )}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationGetOfferCalculationAmountTenureGet(
  //     amount: number,
  //     tenure: number,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     if (amount === null || amount === undefined) {
  //       throw new Error(
  //         'Required parameter amount was null or undefined when calling apiV1LoanOriginationGetOfferCalculationAmountTenureGet.'
  //       );
  //     }

  //     if (tenure === null || tenure === undefined) {
  //       throw new Error(
  //         'Required parameter tenure was null or undefined when calling apiV1LoanOriginationGetOfferCalculationAmountTenureGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/GetOfferCalculation/${encodeURIComponent(
  //         String(amount)
  //       )}/${encodeURIComponent(String(tenure))}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationRejectOfferByCashierLOSIdRejectionReasonIdGet(
  //     lOSId: string,
  //     rejectionReasonId: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     if (lOSId === null || lOSId === undefined) {
  //       throw new Error(
  //         'Required parameter lOSId was null or undefined when calling apiV1LoanOriginationRejectOfferByCashierLOSIdRejectionReasonIdGet.'
  //       );
  //     }

  //     if (rejectionReasonId === null || rejectionReasonId === undefined) {
  //       throw new Error(
  //         'Required parameter rejectionReasonId was null or undefined when calling apiV1LoanOriginationRejectOfferByCashierLOSIdRejectionReasonIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/RejectOfferByCashier/${encodeURIComponent(
  //         String(lOSId)
  //       )}/${encodeURIComponent(String(rejectionReasonId))}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationRejectOfferByOwnerLOSIdRejectionReasonIdGet(
  //     lOSId: string,
  //     rejectionReasonId: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     if (lOSId === null || lOSId === undefined) {
  //       throw new Error(
  //         'Required parameter lOSId was null or undefined when calling apiV1LoanOriginationRejectOfferByOwnerLOSIdRejectionReasonIdGet.'
  //       );
  //     }

  //     if (rejectionReasonId === null || rejectionReasonId === undefined) {
  //       throw new Error(
  //         'Required parameter rejectionReasonId was null or undefined when calling apiV1LoanOriginationRejectOfferByOwnerLOSIdRejectionReasonIdGet.'
  //       );
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'get',
  //       `${
  //         this.basePath
  //       }/api/v1/LoanOrigination/RejectOfferByOwner/${encodeURIComponent(
  //         String(lOSId)
  //       )}/${encodeURIComponent(String(rejectionReasonId))}`,
  //       {
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationSendOfferOTPForOwnerGet(
  //     lOSId?: string,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     let queryParameters = new HttpParams({
  //     //   encoder: new CustomHttpUrlEncodingCodec(),
  //     });
  //     if (lOSId !== undefined && lOSId !== null) {
  //       queryParameters = queryParameters.set('LOSId', <any>lOSId);
  //     }

  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'get',
  //       `${this.basePath}/api/v1/LoanOrigination/SendOfferOTPForOwner`,
  //       {
  //         params: queryParameters,
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationUploadPostForm(
  //     file?: Blob,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<any> {
  //     let headers = this.defaultHeaders;

  //     // to determine the Accept header
  //     let httpHeaderAccepts: string[] = ['application/json'];
  //     const httpHeaderAcceptSelected: string | undefined =
  //       this.configuration.selectHeaderAccept(httpHeaderAccepts);
  //     if (httpHeaderAcceptSelected != undefined) {
  //       headers = headers.set('Accept', httpHeaderAcceptSelected);
  //     }

  //     // to determine the Content-Type header
  //     const consumes: string[] = ['multipart/form-data'];

  //     const canConsumeForm = this.canConsumeForm(consumes);

  //     let formParams: { append(param: string, value: any): void };
  //     let useForm = false;
  //     let convertFormParamsToString = false;
  //     // use FormData to transmit files using content-type "multipart/form-data"
  //     // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
  //     useForm = canConsumeForm;
  //     if (useForm) {
  //       formParams = new FormData();
  //     } else {
  //       formParams = new HttpParams({
  //         // encoder: new CustomHttpUrlEncodingCodec(),
  //       });
  //     }

  //     if (file !== undefined) {
  //       formParams = (formParams.append('file', <any>file) as any) || formParams;
  //     }

  //     return this.httpClient.request<any>(
  //       'post',
  //       `${this.basePath}/api/v1/LoanOrigination/upload`,
  //       {
  //         body: convertFormParamsToString ? formParams.toString() : formParams,
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }

  //   public apiV1LoanOriginationVerifyLoanApplicationPost(
  //     body?: LoanApplicationModel,
  //     observe?: 'body',
  //     reportProgress?: boolean
  //   ): Observable<OfferDetailsModel> {
  //     let headers = this.defaultHeaders;

  //     return this.httpClient.request<OfferDetailsModel>(
  //       'post',
  //       `${this.basePath}/api/v1/LoanOrigination/VerifyLoanApplication`,
  //       {
  //         body: body,
  //         headers: headers,
  //         observe: observe,
  //         reportProgress: reportProgress,
  //       }
  //     );
  //   }
}
